### ISSUE TITLE
Docstring for Functions.

### ISSUE THREAD

**Issue by oke-aditya** [airctic/mantisshrimp#136]
## 🚀 Feature
**Add docstring to all user intended functions**

- Before the first release, it will be nice to have every function documented. Library users can quickly see in their IDE of what this code does.

- It will be easier to debug our code later too as we know what a function does.

Sample docstring: - As suggested by @lgvaz [google napolean style](https://www.sphinx-doc.org/en/master/usage/extensions/napoleon.html), this is how it looks like:

```
def func(arg1, arg2):
    """Summary line.

    Extended description of function.

    Args:
        arg1 (int): Description of arg1
        arg2 (str): Description of arg2

    Returns:
        bool: Description of return value
    """

    return True
```

**Comment by oke-aditya** [comment]
This can be added to docs as API reference too.

**Comment by lgvaz** [comment]
related to #135

**Comment by lgvaz** [comment]
I'll start working on this, adding docstring for the main classes and functions

**Comment by lgvaz** [comment]
Closing in favor of #281
