### ISSUE TITLE
Unifies show_record and show_sample

### ISSUE THREAD

**Issue by lgvaz** [airctic/mantisshrimp#176]
## 🚀 Feature
A `record` and a `sample` are basically the same thing, the only thing that happens is that when indexing a `Dataset` an image is opened from `record['filepath']` and stored into `record['img']`, masks are also opened and all other fields stay the same.

I think we can very comfortably call both stages a `record`, and have only `show_record` that works for both cases.

It's one less abstraction to keep in mind and one less function to maintain. It should also make it easier for beginners.

 @oke-aditya  @ai-fast-track what are your thoughts?

**Comment by ai-fast-track** [comment]
Agree!

**Comment by lgvaz** [comment]
After trying to implement this, it ended up that it made things more confusing.

What we call `samples` and `records` are inherently different. Samples come from `Dataset` and records com from the parsers.

Transforms are applied on samples but no on records, records only have file paths to images while samples have images arrays, etc...
