### ISSUE TITLE
mantisshrimp.all import *

### ISSUE THREAD

**Issue by lgvaz** [airctic/mantisshrimp#184]
## 🚀 Feature
We can curate a namespace that contains all imports for all dependencies (meaning it will only work if you have a full installation):
```
from mantisshrimp.all import *
```

This will import fastai, lightning, albumentations, everything we have support for. Goes very well with the full conda new environment installation.

**Comment by oke-aditya** [comment]
Good Idea but do not use this in the library. This should be just utility for user. Related to #181 #182
