### ISSUE TITLE
How to install efficientdet?

### ISSUE THREAD

**Issue by lgvaz** [airctic/mantisshrimp#246]
None of the pypi installation methods will install efficientdet, the user has to manually install it via `pip install git+...`, but this is not mentioned anywhere in the documentation

Since it's in the core of our library to have soft dependencies, maybe it's a good idea to have a section in the docs explaining what you have to install if you want to use X. Say in the near future we add support for yolo, we need a section explaining the steps to install it (or point to the original installation instructions). This goes well with #245 

@oke-aditya @paras-jain @ai-fast-track , what are your thoughts?

**Comment by oke-aditya** [comment]
This is not exactly soft dependency as model definition is very important to our package, we cannot let it go away from the package.
We can add this to our repo only if we get `.egg` file from the repositories. Also, we need to check what dependency these repositories use, if they are minimal we can package them.

**Comment by lgvaz** [comment]
It's a soft dependency, mantis does not fail to import if you don't have efficientdet

Let's say you only want to train faster_rcnn, you shouldn't have to install efficientdet for that. And this should be true for every new model that we add

**Comment by oke-aditya** [comment]
What if we get `.egg` file from this repo after a few months. Can we bundle it together ?

**Comment by lgvaz** [comment]
Getting the `.egg` files just seem to hacky, we don't want to deal with that

It's actually easier to have instructions on how to install the package

**Comment by oke-aditya** [comment]
The problem is when we ship for release 0.1. The package from github repo may get updated and hence incompatibly with release. Suppose we lock our dependencies when it was working fine, then we receive an update from these packages that break stuff.
So it is safer to ship it with the corresponding `.egg` file.

**Comment by lgvaz** [comment]
The efficientdet dependency will also be locked to a specific version on our release, why are updates going to break stuff?

**Comment by oke-aditya** [comment]
How will we lock efficient det version ? Do we lock to some commit stamp?

**Comment by lgvaz** [comment]
We lock a commit stamp, yes

**Comment by oke-aditya** [comment]
Can we build a wheel for that commit stamp and provide as assets with our repo ?

**Comment by lgvaz** [comment]
My answer is: I don't know, and it should not be our priority now, not for 0.1.0

I'll start a 0.2.0 roadmap and add this there

**Comment by lgvaz** [comment]
Let's stick with adding installation instructions for efficient for this release, I'll close this one once we do that

**Comment by lgvaz** [comment]
Efficient is now installed with `[all]` =)
