### ISSUE TITLE
Pin Versions for release.

### ISSUE THREAD

**Issue by oke-aditya** [airctic/mantisshrimp#247]
## 🐛 Release

We need to pin the versions before first release.

Do some trial runs for release 0.1.0 as rc1, rc2, rc3 and check if they work.

Also, we need to familiarize how to release stuff on GitHub, we need a proper description of release as well.

**Comment by lgvaz** [comment]
Related to #244 , let's discuss and understand this before we merge that one

Let's try to follow lightning structure, their releases are very well organized and clean

**Comment by oke-aditya** [comment]
K 👍

**Comment by lgvaz** [comment]
Required versions are pinned, for additional dependency management follow #267
