### ISSUE TITLE
Update the conda environment installation

### ISSUE THREAD

**Issue by oke-aditya** [airctic/mantisshrimp#248]
## 🐛 Bug

We need to update the conda environment installation.
User should be able to download the `.yml` file and simply use this.

This should also be changed in Readme. The steps can be made shorter. Simply download and run conda install command.

**Comment by lgvaz** [comment]
With #265 installing all dependencies will be as easy as `pip install -e .[all]`.

Maybe we should remove conda installation and just go with pip?

**Comment by oke-aditya** [comment]
Yes. Also people can simply do
`conda create env --name mantis`
I guess this will create a fresh environment. Then people can simply do `pip install mantisshrimp[all]`

**Comment by lgvaz** [comment]
And we get back to the annoying pycocotools again...

Pycocotools `setup.py` requires that both cython and numpy are installed previously (this means, before even running **our** `setup.py`, you can see it failing on #265)

There are no easy ways of circurvating this issue, a hacky solution is described [here](https://stackoverflow.com/questions/19919905/how-to-bootstrap-numpy-installation-in-setup-py)

**Comment by lgvaz** [comment]
Trying to solve it with [this](https://stackoverflow.com/a/54138355/6772672)
