### ISSUE TITLE
Update Manifest.in file for Mantisshrimp

### ISSUE THREAD

**Issue by oke-aditya** [airctic/mantisshrimp#253]
## 🚀 Feature

We need to have a proper init file like lightning has. It has a lot of starter code that can be used.
Have a look [here](https://github.com/PyTorchLightning/pytorch-lightning/blob/master/pytorch_lightning/__init__.py)
It makes these things possible
```
import mantisshirmp as ms
print(ms.__version__)
```
Note the above thing is possible now as I have added this while merging CI change.

**Comment by lgvaz** [comment]
Can you explain your reason why you think our current `__init__.py` isn't good enough?

All the other information like description is in `settings.py`, I actually think this makes things more organized

**Comment by oke-aditya** [comment]
If we remove __version__ from mantisshrimp init will it work. ?

We do have these stuff in setup.py. So does Lightning have. I will look into why they did so. 

Maybe we don't need it. I'm unsure.

**Comment by oke-aditya** [comment]
Actually we don't need to update there as you said.
What they did was defined the stuff in init file and then they used it `setup.py`. Instead, we have defined it in `settings.ini`.

But we need an update for MANIFEST.in. It is currently packaging unnecassary stuff too. We can exclude some more things.
