### ISSUE TITLE
Move Repostories to Organization

### ISSUE THREAD

**Issue by oke-aditya** [airctic/mantisshrimp#262]
## 🚀 Feature

We need to shift the streamlit and WandB repositories to airctic

Streamlit repo [link](https://github.com/oke-aditya/mantisshrimp_streamlit)

WandB under progress [link](https://github.com/oke-aditya/mantisshrimp_wandb)

**Comment by lgvaz** [comment]
Okay! I think we're finally ready for this 🎊 

@oke-aditya, can you transfer the repos to `lgvaz`? I'll then add to the organization

**Comment by oke-aditya** [comment]
That means. I should transfer ownership to to @lgvaz   then you will add it right ?

**Comment by lgvaz** [comment]
Yep =)

**Comment by oke-aditya** [comment]
Requested for transfer. 👍 Thought we might end up in messing github teams deployment. Coz it is tied to my repo. We can shift.

**Comment by lgvaz** [comment]
Alright, here it's! https://github.com/airctic/mantisshrimp_streamlit
