### ISSUE TITLE
Update the Faster RCNN  README to include a Usage part 

### ISSUE THREAD

**Issue by ai-fast-track** [airctic/mantisshrimp#323]
## 📓 Documentation Update
**What part of documentation was unclear or wrong?**
It would be good to have a Usage section that explains how to use both the Faster RCNN model and its corresponding DataLoaders

**Comment by lgvaz** [comment]
Is it a good idea to just point to the tutorial using fasterrcnn?

**Comment by ai-fast-track** [comment]
This is a README that shows the Usage + the a short description of the original paper + plus a list of of blogs, and implementations that are not shown in the Tutorial.

**Comment by ai-fast-track** [comment]
Implemented in the PR #332
