### ISSUE TITLE
Clean mantis root folder

### ISSUE THREAD

**Issue by lgvaz** [airctic/mantisshrimp#327]
We need to reduce the clutter on the root folder:

 Files like `MODEL_FASTER_RCNN.md `, `README_MKDOCS.md`, `ABOUT.md` can probably be moved under `docs/`

`images/` can be moved under `docs/`,

Maybe we can also move `notebooks/` and `examples/` under `docs/`? I'm not sure about this one though, being on the root folder can facilitate exploration.

`samples` can probably be moved under `tests`. That would require additional refactoring because of `test_utils` though...

**Comment by oke-aditya** [comment]
I will try cleaning this up. 👍 md files might create a mess later on.

**Comment by ai-fast-track** [comment]
Closed: done in the PR #367
